blank_issues_enabled: true

contact_links:
  - name: Documentation
    url: https://gitlab.com/florent_fougeres/test-qgis-plugin-templater-gh
    about: Please read carefully the documentation before to submit an issue.
